[package]
name = "word_count_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = { version = "5.5.3", features = ["rayon"] }
jieba-rs = "0.6.8"
rayon = "1.8.0"
regex = "1.10.2"
serde = { version = "1.0.193"}
serde_json = "1.0.108"
r2d2 = "0.8.10"
r2d2_sqlite = "0.23.0"
rusqlite = { version = "0.30.0", features = ["bundled"] }
