[package]
name = "word_count_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.3"
csv = "1.3.0"
jieba-rs = "0.6.8"
pinyin = "0.10.0"
rayon = "1.8.0"
regex = "1.10.2"
serde = { version = "1.0.193"}
serde_json = "1.0.108"
